# Generated by Django 3.0.2 on 2020-01-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardInteraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADCchannle',
            new_name='ADCchannel',
        ),
    ]
