# Generated by Django 3.0.2 on 2020-01-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardInteraction', '0002_auto_20200122_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPGAconfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
