# Generated by Django 3.0.2 on 2020-01-22 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardInteraction', '0003_fpgaconffiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpgaconffiles',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fpgaconffiles',
            name='docfile',
            field=models.FileField(upload_to='FPGAconfigDatabase/%Y/%m/%d'),
        ),
    ]
