# Generated by Django 3.0.2 on 2020-01-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardInteraction', '0004_auto_20200122_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcsensorreading',
            name='reading',
            field=models.FloatField(),
        ),
    ]
